//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIARClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FIARClient.ServiceReference1.OpponentDisconnectedFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FIARClient.ServiceReference1.OpponentNotAvailableFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FIARClient.ServiceReference1.PlayerDoesntExistInDataBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FIARClient.ServiceReference1.PlayerAlreadyConnectedFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FIARClient.ServiceReference1.PlayerAlreadyExistsInDataBase))]
    public partial class CustomFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpponentDisconnectedFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
    [System.SerializableAttribute()]
    public partial class OpponentDisconnectedFault : FIARClient.ServiceReference1.CustomFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpponentNotAvailableFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
    [System.SerializableAttribute()]
    public partial class OpponentNotAvailableFault : FIARClient.ServiceReference1.CustomFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDoesntExistInDataBase", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
    [System.SerializableAttribute()]
    public partial class PlayerDoesntExistInDataBase : FIARClient.ServiceReference1.CustomFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerAlreadyConnectedFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
    [System.SerializableAttribute()]
    public partial class PlayerAlreadyConnectedFault : FIARClient.ServiceReference1.CustomFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerAlreadyExistsInDataBase", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
    [System.SerializableAttribute()]
    public partial class PlayerAlreadyExistsInDataBase : FIARClient.ServiceReference1.CustomFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
    [System.SerializableAttribute()]
    public partial class PlayerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LosesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> PlayedAgainstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FIARClient.ServiceReference1.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Games {
            get {
                return this.GamesField;
            }
            set {
                if ((this.GamesField.Equals(value) != true)) {
                    this.GamesField = value;
                    this.RaisePropertyChanged("Games");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Loses {
            get {
                return this.LosesField;
            }
            set {
                if ((this.LosesField.Equals(value) != true)) {
                    this.LosesField = value;
                    this.RaisePropertyChanged("Loses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> PlayedAgainst {
            get {
                return this.PlayedAgainstField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayedAgainstField, value) != true)) {
                    this.PlayedAgainstField = value;
                    this.RaisePropertyChanged("PlayedAgainst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FIARClient.ServiceReference1.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disconnected = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Playing = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
    [System.SerializableAttribute()]
    public partial class GameInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GameOverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameStartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Player1PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Player1_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Player1_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Player2PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Player2_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Player2_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinnerScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Winner_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameId {
            get {
                return this.GameIdField;
            }
            set {
                if ((this.GameIdField.Equals(value) != true)) {
                    this.GameIdField = value;
                    this.RaisePropertyChanged("GameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GameOver {
            get {
                return this.GameOverField;
            }
            set {
                if ((this.GameOverField.Equals(value) != true)) {
                    this.GameOverField = value;
                    this.RaisePropertyChanged("GameOver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameStartDate {
            get {
                return this.GameStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.GameStartDateField, value) != true)) {
                    this.GameStartDateField = value;
                    this.RaisePropertyChanged("GameStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameStartTime {
            get {
                return this.GameStartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameStartTimeField, value) != true)) {
                    this.GameStartTimeField = value;
                    this.RaisePropertyChanged("GameStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player1Points {
            get {
                return this.Player1PointsField;
            }
            set {
                if ((this.Player1PointsField.Equals(value) != true)) {
                    this.Player1PointsField = value;
                    this.RaisePropertyChanged("Player1Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player1_id {
            get {
                return this.Player1_idField;
            }
            set {
                if ((this.Player1_idField.Equals(value) != true)) {
                    this.Player1_idField = value;
                    this.RaisePropertyChanged("Player1_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Player1_name {
            get {
                return this.Player1_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Player1_nameField, value) != true)) {
                    this.Player1_nameField = value;
                    this.RaisePropertyChanged("Player1_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player2Points {
            get {
                return this.Player2PointsField;
            }
            set {
                if ((this.Player2PointsField.Equals(value) != true)) {
                    this.Player2PointsField = value;
                    this.RaisePropertyChanged("Player2Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Player2_id {
            get {
                return this.Player2_idField;
            }
            set {
                if ((this.Player2_idField.Equals(value) != true)) {
                    this.Player2_idField = value;
                    this.RaisePropertyChanged("Player2_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Player2_name {
            get {
                return this.Player2_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Player2_nameField, value) != true)) {
                    this.Player2_nameField = value;
                    this.RaisePropertyChanged("Player2_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Winner {
            get {
                return this.WinnerField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerField, value) != true)) {
                    this.WinnerField = value;
                    this.RaisePropertyChanged("Winner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WinnerScore {
            get {
                return this.WinnerScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerScoreField, value) != true)) {
                    this.WinnerScoreField = value;
                    this.RaisePropertyChanged("WinnerScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Winner_id {
            get {
                return this.Winner_idField;
            }
            set {
                if ((this.Winner_idField.Equals(value) != true)) {
                    this.Winner_idField = value;
                    this.RaisePropertyChanged("Winner_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoveResult", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
    public enum MoveResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YouWon = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YouLost = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draw = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameOn = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerLeft = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IlligelMove = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFIARService", CallbackContract=typeof(FIARClient.ServiceReference1.IFIARServiceCallback))]
    public interface IFIARService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/RegisterPlayer", ReplyAction="http://tempuri.org/IFIARService/RegisterPlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FIARClient.ServiceReference1.PlayerAlreadyExistsInDataBase), Action="http://tempuri.org/IFIARService/RegisterPlayerPlayerAlreadyExistsInDataBaseFault", Name="PlayerAlreadyExistsInDataBase", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
        void RegisterPlayer(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/RegisterPlayer", ReplyAction="http://tempuri.org/IFIARService/RegisterPlayerResponse")]
        System.Threading.Tasks.Task RegisterPlayerAsync(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/InvitationSend", ReplyAction="http://tempuri.org/IFIARService/InvitationSendResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FIARClient.ServiceReference1.OpponentDisconnectedFault), Action="http://tempuri.org/IFIARService/InvitationSendOpponentDisconnectedFaultFault", Name="OpponentDisconnectedFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
        [System.ServiceModel.FaultContractAttribute(typeof(FIARClient.ServiceReference1.OpponentNotAvailableFault), Action="http://tempuri.org/IFIARService/InvitationSendOpponentNotAvailableFaultFault", Name="OpponentNotAvailableFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
        bool InvitationSend(string fromPlayer, string toPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/InvitationSend", ReplyAction="http://tempuri.org/IFIARService/InvitationSendResponse")]
        System.Threading.Tasks.Task<bool> InvitationSendAsync(string fromPlayer, string toPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/PlayerLogin", ReplyAction="http://tempuri.org/IFIARService/PlayerLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FIARClient.ServiceReference1.PlayerDoesntExistInDataBase), Action="http://tempuri.org/IFIARService/PlayerLoginPlayerDoesntExistInDataBaseFault", Name="PlayerDoesntExistInDataBase", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
        [System.ServiceModel.FaultContractAttribute(typeof(FIARClient.ServiceReference1.PlayerAlreadyConnectedFault), Action="http://tempuri.org/IFIARService/PlayerLoginPlayerAlreadyConnectedFaultFault", Name="PlayerAlreadyConnectedFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
        void PlayerLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/PlayerLogin", ReplyAction="http://tempuri.org/IFIARService/PlayerLoginResponse")]
        System.Threading.Tasks.Task PlayerLoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/SetAsAvailablePlayer", ReplyAction="http://tempuri.org/IFIARService/SetAsAvailablePlayerResponse")]
        void SetAsAvailablePlayer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/SetAsAvailablePlayer", ReplyAction="http://tempuri.org/IFIARService/SetAsAvailablePlayerResponse")]
        System.Threading.Tasks.Task SetAsAvailablePlayerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/GetAllPlayers", ReplyAction="http://tempuri.org/IFIARService/GetAllPlayersResponse")]
        System.Collections.Generic.List<FIARClient.ServiceReference1.PlayerInfo> GetAllPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/GetAllPlayers", ReplyAction="http://tempuri.org/IFIARService/GetAllPlayersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FIARClient.ServiceReference1.PlayerInfo>> GetAllPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/GetPlayersGames", ReplyAction="http://tempuri.org/IFIARService/GetPlayersGamesResponse")]
        System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo> GetPlayersGames(string player1, string player2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/GetPlayersGames", ReplyAction="http://tempuri.org/IFIARService/GetPlayersGamesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo>> GetPlayersGamesAsync(string player1, string player2);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFIARService/PlayerLogout")]
        void PlayerLogout(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFIARService/PlayerLogout")]
        System.Threading.Tasks.Task PlayerLogoutAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/Init", ReplyAction="http://tempuri.org/IFIARService/InitResponse")]
        void Init();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/Init", ReplyAction="http://tempuri.org/IFIARService/InitResponse")]
        System.Threading.Tasks.Task InitAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFIARService/Disconnected")]
        void Disconnected(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFIARService/Disconnected")]
        System.Threading.Tasks.Task DisconnectedAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/ReportMove", ReplyAction="http://tempuri.org/IFIARService/ReportMoveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FIARClient.ServiceReference1.OpponentDisconnectedFault), Action="http://tempuri.org/IFIARService/ReportMoveOpponentDisconnectedFaultFault", Name="OpponentDisconnectedFault", Namespace="http://schemas.datacontract.org/2004/07/WcfFIARService")]
        FIARClient.ServiceReference1.MoveResult ReportMove(string username, int col);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/ReportMove", ReplyAction="http://tempuri.org/IFIARService/ReportMoveResponse")]
        System.Threading.Tasks.Task<FIARClient.ServiceReference1.MoveResult> ReportMoveAsync(string username, int col);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/GetAvalibalePlayers", ReplyAction="http://tempuri.org/IFIARService/GetAvalibalePlayersResponse")]
        System.Collections.Generic.List<FIARClient.ServiceReference1.PlayerInfo> GetAvalibalePlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/GetAvalibalePlayers", ReplyAction="http://tempuri.org/IFIARService/GetAvalibalePlayersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FIARClient.ServiceReference1.PlayerInfo>> GetAvalibalePlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/GetEndedGames", ReplyAction="http://tempuri.org/IFIARService/GetEndedGamesResponse")]
        System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo> GetEndedGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/GetEndedGames", ReplyAction="http://tempuri.org/IFIARService/GetEndedGamesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo>> GetEndedGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/GetOngoingGames", ReplyAction="http://tempuri.org/IFIARService/GetOngoingGamesResponse")]
        System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo> GetOngoingGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/GetOngoingGames", ReplyAction="http://tempuri.org/IFIARService/GetOngoingGamesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo>> GetOngoingGamesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFIARServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIARService/SendInvite", ReplyAction="http://tempuri.org/IFIARService/SendInviteResponse")]
        bool SendInvite(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFIARService/OtherPlayerMoved")]
        void OtherPlayerMoved(FIARClient.ServiceReference1.MoveResult result, int col);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFIARService/OtherPlayerDisconnected")]
        void OtherPlayerDisconnected();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFIARService/UpdateClients")]
        void UpdateClients(System.Collections.Generic.List<FIARClient.ServiceReference1.PlayerInfo> players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFIARService/StartGame")]
        void StartGame();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFIARServiceChannel : FIARClient.ServiceReference1.IFIARService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FIARServiceClient : System.ServiceModel.DuplexClientBase<FIARClient.ServiceReference1.IFIARService>, FIARClient.ServiceReference1.IFIARService {
        
        public FIARServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FIARServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FIARServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FIARServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FIARServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RegisterPlayer(string username, string pass) {
            base.Channel.RegisterPlayer(username, pass);
        }
        
        public System.Threading.Tasks.Task RegisterPlayerAsync(string username, string pass) {
            return base.Channel.RegisterPlayerAsync(username, pass);
        }
        
        public bool InvitationSend(string fromPlayer, string toPlayer) {
            return base.Channel.InvitationSend(fromPlayer, toPlayer);
        }
        
        public System.Threading.Tasks.Task<bool> InvitationSendAsync(string fromPlayer, string toPlayer) {
            return base.Channel.InvitationSendAsync(fromPlayer, toPlayer);
        }
        
        public void PlayerLogin(string username, string password) {
            base.Channel.PlayerLogin(username, password);
        }
        
        public System.Threading.Tasks.Task PlayerLoginAsync(string username, string password) {
            return base.Channel.PlayerLoginAsync(username, password);
        }
        
        public void SetAsAvailablePlayer(string username) {
            base.Channel.SetAsAvailablePlayer(username);
        }
        
        public System.Threading.Tasks.Task SetAsAvailablePlayerAsync(string username) {
            return base.Channel.SetAsAvailablePlayerAsync(username);
        }
        
        public System.Collections.Generic.List<FIARClient.ServiceReference1.PlayerInfo> GetAllPlayers() {
            return base.Channel.GetAllPlayers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FIARClient.ServiceReference1.PlayerInfo>> GetAllPlayersAsync() {
            return base.Channel.GetAllPlayersAsync();
        }
        
        public System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo> GetPlayersGames(string player1, string player2) {
            return base.Channel.GetPlayersGames(player1, player2);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo>> GetPlayersGamesAsync(string player1, string player2) {
            return base.Channel.GetPlayersGamesAsync(player1, player2);
        }
        
        public void PlayerLogout(string username) {
            base.Channel.PlayerLogout(username);
        }
        
        public System.Threading.Tasks.Task PlayerLogoutAsync(string username) {
            return base.Channel.PlayerLogoutAsync(username);
        }
        
        public void Init() {
            base.Channel.Init();
        }
        
        public System.Threading.Tasks.Task InitAsync() {
            return base.Channel.InitAsync();
        }
        
        public void Disconnected(string username) {
            base.Channel.Disconnected(username);
        }
        
        public System.Threading.Tasks.Task DisconnectedAsync(string username) {
            return base.Channel.DisconnectedAsync(username);
        }
        
        public FIARClient.ServiceReference1.MoveResult ReportMove(string username, int col) {
            return base.Channel.ReportMove(username, col);
        }
        
        public System.Threading.Tasks.Task<FIARClient.ServiceReference1.MoveResult> ReportMoveAsync(string username, int col) {
            return base.Channel.ReportMoveAsync(username, col);
        }
        
        public System.Collections.Generic.List<FIARClient.ServiceReference1.PlayerInfo> GetAvalibalePlayers() {
            return base.Channel.GetAvalibalePlayers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FIARClient.ServiceReference1.PlayerInfo>> GetAvalibalePlayersAsync() {
            return base.Channel.GetAvalibalePlayersAsync();
        }
        
        public System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo> GetEndedGames() {
            return base.Channel.GetEndedGames();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo>> GetEndedGamesAsync() {
            return base.Channel.GetEndedGamesAsync();
        }
        
        public System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo> GetOngoingGames() {
            return base.Channel.GetOngoingGames();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FIARClient.ServiceReference1.GameInfo>> GetOngoingGamesAsync() {
            return base.Channel.GetOngoingGamesAsync();
        }
    }
}
